name: CI - Build Backend

on:
  pull_request:
    branches:
      - master
    paths:
      - backend/**
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_URL: jdbc:postgresql://localhost:5332/customer
      DB_USERNAME: anassabbou
      DB_PASSWORD: password
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ env.DB_USERNAME }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
          POSTGRES_DB: customer
        ports:
          - 5332:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: ./backend
    steps: # github.com/marketplace
      - uses: actions/checkout@v4
        name: Clone Repo to Github Action
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build and run Unit/integration Tests with Maven
        run: mvn -ntp -B verify # Download all deps & plugins
